name: Notify Evaluation Server

on:
  pull_request_target:
    types: [opened, synchronize]
  
jobs:
  notify:
    runs-on: ubuntu-latest
    # Add permissions to run without approval
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          
      - name: Debug info
        run: |
          echo "Token generated successfully"
          echo "Attempting to notify repository: AGARBAC/secret-test"
          
      - name: Notify evaluation server
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ steps.generate_token.outputs.token }}
          repository: AGARBAC/secret-test
          event-type: candidate-pr-created
          client-payload: '{"repo": "${{ github.repository }}", "pr_number": "${{ github.event.pull_request.number }}", "ref": "${{ github.event.pull_request.head.ref }}", "sha": "${{ github.event.pull_request.head.sha }}", "fork_owner": "${{ github.event.pull_request.head.repo.owner.login }}"}' 