name: Notify Evaluation Server

on:
  pull_request_target:
    types: [opened, synchronize]
  
jobs:
  notify:
    runs-on: ubuntu-latest
    # Add permissions to run without approval
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Debug info
        run: |
          echo "Attempting to notify repository: agbackhoff/secret-test"
          echo "Pull request details:"
          echo "  PR number: ${{ github.event.pull_request.number }}"
          echo "  Repo: ${{ github.repository }}"
          echo "  Head ref: ${{ github.event.pull_request.head.ref }}"
          echo "  Fork owner: ${{ github.event.pull_request.head.repo.owner.login }}"
          
      - name: Notify evaluation server
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.EVAL_PAT }}
          repository: agbackhoff/secret-test
          event-type: candidate-pr-created
          client-payload: '{"repo": "${{ github.repository }}", "pr_number": "${{ github.event.pull_request.number }}", "ref": "${{ github.event.pull_request.head.ref }}", "sha": "${{ github.event.pull_request.head.sha }}", "fork_owner": "${{ github.event.pull_request.head.repo.owner.login }}"}' 